const products = [
    // THE BIRMINGHAM EDIT (PEAKY BLINDERS)
    {
        id: 12,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Signature Herringbone Newsboy Cap",
        description: "A heritage classic reimagined. This structured herringbone newsboy cap channels early 20th-century craftsmanship with a contemporary edge.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Newsboy%20Cap.webp",
        image2: "images/Newsboy%20Cap.webp",
        affiliateLink: "https://amzn.to/4cahnIL",
        buttonText: "Shop on Amazon"
    },
    {
        id: 13,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Heritage Leather Braces",
        description: "Hand-stitched leather braces that define the silhouette. A statement accessory rooted in English tailoring tradition.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Leather%20Suspender.webp",
        image2: "images/Leather%20Suspender.webp",
        affiliateLink: "https://amzn.to/4bNdmJQ",
        buttonText: "Shop on Amazon"
    },
    {
        id: 14,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Cable-Knit Heritage Sweater",
        description: "Chunky cable-knit construction in a rich neutral tone. Layers effortlessly under a structured coat or stands alone with quiet authority.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Casual%20Twisted%20Knitted%20Pullover%20Sweater.webp",
        image2: "images/Casual%20Twisted%20Knitted%20Pullover%20Sweater.webp",
        affiliateLink: "https://amzn.to/4lOp7o9",
        buttonText: "Shop on Amazon"
    },
    {
        id: 15,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Classic Double-Breasted Trench",
        description: "A timeless double-breasted silhouette in water-resistant fabric. This coat anchors any look with confident, lasting elegance.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Casual%20Trench%20Coat.webp",
        image2: "images/Casual%20Trench%20Coat.webp",
        affiliateLink: "https://amzn.to/3PvfWNc",
        buttonText: "Shop on Amazon"
    },
    {
        id: 16,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Tweed Herringbone Tailored Trousers",
        description: "Tailored tweed trousers in a classic herringbone weave. The slightly tapered leg and heritage fabric make these a cornerstone of any refined wardrobe.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Tweed%20Herringbone%20Vintage%20trouser.webp",
        image2: "images/Tweed%20Herringbone%20Vintage%20trouser.webp",
        affiliateLink: "https://amzn.to/41of93g",
        buttonText: "Shop on Amazon"
    },
    {
        id: 17,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Antique Mechanical Pocket Watch",
        description: "An intricate mechanical pocket watch with antique gold toning. A conversation piece that bridges the past and present.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Vintage%20Pocket%20Watch.webp",
        image2: "images/Vintage%20Pocket%20Watch.webp",
        affiliateLink: "https://amzn.to/4bwhz5T",
        buttonText: "Shop on Amazon"
    },
    {
        id: 18,
        outfitId: "birmingham-edit",
        category: "men",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Cap-Toe Heritage Combat Boots",
        description: "Cap-toe leather boots with a Goodyear-welted sole. Built for longevity, styled for impact.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/Rubber-Lace-up%20Boot.webp",
        image2: "images/Rubber-Lace-up%20Boot.webp",
        affiliateLink: "https://amzn.to/3NWBP7E",
        buttonText: "Shop on Amazon"
    },
    // THE NAVY & IVORY EDIT
    {
        id: 19,
        outfitId: "navy-ivory-edit",
        category: "women",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Oversized Navy Wool-Blend Maxi Coat",
        description: "Drama and polish in equal measure. This oversized wool-blend maxi coat drapes with architectural confidence over any silhouette.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/navy-maxi-coat.webp",
        image2: "images/navy-maxi-coat.webp",
        affiliateLink: "https://amzn.to/4rZIz2H",
        buttonText: "Shop on Amazon"
    },
    {
        id: 20,
        outfitId: "navy-ivory-edit",
        category: "women",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Classic Navy Crewneck Knit Sweater",
        description: "The understated backbone of the capsule wardrobe. Moves seamlessly from weekend mornings to styled evenings.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/navy-crewneck-sweater.webp",
        image2: "images/navy-crewneck-sweater.webp",
        affiliateLink: "https://amzn.to/4t1lm0O",
        buttonText: "Shop on Amazon"
    },
    {
        id: 21,
        outfitId: ["navy-ivory-edit", "blush-ivory-edit"],
        category: "women",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Ivory Wide-Leg Pleated Trousers",
        description: "Wide-leg pleated trousers in crisp ivory. The high waist elongates while the relaxed leg breathes with effortless modern grace.",
        price: "Check Price",
        badge: "Style Inspiration",
        trending: "Old Money Summer ↑400%",
        image1: "images/ivory-wide-leg-pants.webp",
        image2: "images/ivory-wide-leg-pants.webp",
        affiliateLink: "https://amzn.to/4uMKKt7",
        buttonText: "Shop on Amazon"
    },
    {
        id: 22,
        outfitId: "navy-ivory-edit",
        category: "women",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Structured Lime Green Top-Handle Bag",
        description: "A burst of structured colour. This lime green top-handle bag is the deliberate contrast that transforms a neutral palette into a statement.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/lime-green-bag.webp",
        image2: "images/lime-green-bag.webp",
        affiliateLink: "https://amzn.to/3PGH0Jm",
        buttonText: "Shop on Amazon"
    },
    {
        id: 23,
        outfitId: "navy-ivory-edit",
        category: "women",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Pointed-Toe Ivory Ankle Booties",
        description: "Pointed-toe booties in soft ivory leather. A refined finishing touch that sharpens every look from the ground up.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/ivory-ankle-booties.webp",
        image2: "images/ivory-ankle-booties.webp",
        affiliateLink: "https://amzn.to/47mlIH2",
        buttonText: "Shop on Amazon"
    },
    // THE pink MEADOW EDIT
    {
        id: 24,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Vintage Gingham Button-Up Blouse",
        description: "A sweet nod to vintage charm. This tan gingham button-up blouse features a peter pan collar for a look that photographs beautifully.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/gingham-blouse.webp",
        image2: "images/gingham-blouse.webp",
        affiliateLink: "https://amzn.to/4sshpSY",
        buttonText: "Shop on Amazon"
    },
    {
        id: 25,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Stretchy Cotton Suspender Skirt",
        description: "Stretchy cotton suspender skirt in warm tones. Easy to style, comfortable to wear, and endlessly charming.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/suspender-skirt.webp",
        image2: "images/suspender-skirt.webp",
        affiliateLink: "https://amzn.to/4t5xvSp",
        buttonText: "Shop on Amazon"
    },
    {
        id: 26,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Little Bear Leather Crossbody",
        description: "A whimsical little bear crossbody that doubles as a playful accessory and a practical carry-all for the little adventurer.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/bear-crossbody.webp",
        image2: "images/bear-crossbody.webp",
        affiliateLink: "https://amzn.to/3NNLeOJ",
        buttonText: "Shop on Amazon"
    },
    {
        id: 27,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Classic T-Strap Mary Jane Flats",
        description: "Classic T-strap mary jane flats in smooth leather. Timeless, practical, and utterly sweet for any occasion.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/mary-jane-flats.webp",
        image2: "images/mary-jane-flats.webp",
        affiliateLink: "https://amzn.to/4dKmNw9",
        buttonText: "Shop on Amazon"
    },
    {
        id: 28,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Delicate Ruffle-Trim Ankle Socks",
        description: "Delicate ruffle-trim ankle socks that add a touch of feminine detail to any look from the ankles up.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/ruffle-socks.webp",
        image2: "images/ruffle-socks.webp",
        affiliateLink: "https://amzn.to/3O0Os1u",
        buttonText: "Shop on Amazon"
    },
    {
        id: 29,
        outfitId: "pink-meadow-edit",
        category: "kids",
        type: "fashion",
        brand: "SELENE LUXE",
        name: "Wide Fabric Knot Headband",
        description: "A wide fabric knot headband that keeps hair styled while adding a polished finishing touch to any look.",
        price: "Check Price",
        badge: "Style Inspiration",
        image1: "images/white-headband.webp",
        image2: "images/white-headband.webp",
        affiliateLink: "https://amzn.to/4uYG4QX",
        buttonText: "Shop on Amazon"
    },
    {
        id: 30,
        outfitId: "cosmetics-skincare-edit",
        category: "cosmetics",
        type: "lifestyle",
        brand: "SELENE LUXE",
        name: "Berry Lip Sleeping Mask",
        description: "A rich overnight lip treatment that seals in moisture while you sleep. Wake up with softer, plumper lips — effortlessly.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "K-Beauty ↑",
        image1: "images/lineage1.webp",
        image2: "images/lineage1.webp",
        affiliateLink: "https://amzn.to/41BzvX7",
        buttonText: "Shop on Amazon"
    },
    {
        id: 31,
        outfitId: "cosmetics-skincare-edit",
        category: "cosmetics",
        type: "lifestyle",
        brand: "COSRX",
        name: "Snail Mucin Power Repairing Essence",
        description: "96% snail secretion filtrate in a lightweight essence. This cult-favourite K-beauty formula repairs, hydrates, and visibly reduces the appearance of fine lines.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Glass Skin ↑",
        image1: "images/COSRX1.webp",
        image2: "images/COSRX1.webp",
        affiliateLink: "https://amzn.to/4c4Vj1R",
        buttonText: "Shop on Amazon"
    },
    {
        id: 32,
        outfitId: "cosmetics-skincare-edit",
        category: "cosmetics",
        type: "lifestyle",
        brand: "COSRX",
        name: "Advanced Snail 96 Mucin Essence",
        description: "A concentrated snail mucin essence that works deeply to restore the skin's natural barrier. The gold standard of K-beauty hydration.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Glass Skin ↑",
        image1: "images/COSRX2.webp",
        image2: "images/COSRX2.webp",
        affiliateLink: "https://amzn.to/4crVMMW",
        buttonText: "Shop on Amazon"
    },
    {
        id: 33,
        category: "women",
        type: "fashion",
        brand: "HEAWISH",
        name: "Women's Floral Ballet Flats",
        description: "Floral-embroidered ballet flats that bring feminine delicacy to any ensemble. Available in nine colours — from classic white to bold red.",
        price: "Check Price",
        badge: "Style Inspiration",
        trending: "Ballet Core ↑",
        image1: "images/HEAWISH Women's Floral Ballet Flats white.webp",
        image2: "images/HEAWISH Women's Floral Ballet Flats white.webp",
        affiliateLink: "https://www.amazon.com/dp/B08CDGSKJH?tag=seleneluxe05-20",
        buttonText: "Shop on Amazon",
        variants: [
            {
                color: "White",
                colorCode: "#ffffff",
                image: "images/HEAWISH Women's Floral Ballet Flats white.webp"
            },
            {
                color: "Beige",
                colorCode: "#f5f5dc",
                image: "images/HEAWISH Women's Floral Ballet Flats beige.webp"
            },
            {
                color: "Black",
                colorCode: "#000000",
                image: "images/HEAWISH Women's Floral Ballet Flats black.webp"
            },
            {
                color: "Grey",
                colorCode: "#808080",
                image: "images/HEAWISH Women's Floral Ballet Flats grey.webp"
            },
            {
                color: "Chocolate",
                colorCode: "#7b3f00",
                image: "images/HEAWISH Women's Floral Ballet Flats chocolate.webp"
            },
            {
                color: "Light Blue",
                colorCode: "#add8e6",
                image: "images/HEAWISH Women's Floral Ballet Flats light blue.webp"
            },
            {
                color: "Light Green",
                colorCode: "#90ee90",
                image: "images/HEAWISH Women's Floral Ballet Flats light green.webp"
            },
            {
                color: "Pink",
                colorCode: "#ffc0cb",
                image: "images/HEAWISH Women's Floral Ballet Flats pink.webp"
            },
            {
                color: "Red",
                colorCode: "#ff0000",
                image: "images/HEAWISH Women's Floral Ballet Flats red.webp"
            }
        ]
    },
    {
        id: 34,
        category: "women",
        type: "fashion",
        brand: "WOOSEA",
        name: "Women's Split Bodycon Mermaid Evening Cocktail Long Dress",
        description: "A sculptural mermaid silhouette with a daring thigh split. This evening dress commands attention from every angle.",
        price: "Check Price",
        badge: "Style Inspiration",
        trending: "Trending Now",
        image1: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress black.webp",
        image2: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress black.webp",
        affiliateLink: "https://www.amazon.com/WOOSEA-Bodycon-Mermaid-Evening-Cocktail/dp/B08CHKPR4H?tag=seleneluxe05-20",
        buttonText: "Shop on Amazon",
        variants: [
            {
                color: "Black",
                colorCode: "#000000",
                image: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress black.webp"
            },
            {
                color: "Purple",
                colorCode: "#800080",
                image: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress purple.webp"
            },
            {
                color: "Navy Blue",
                colorCode: "#000080",
                image: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress navy blue.webp"
            },
            {
                color: "Royal Blue",
                colorCode: "#4169E1",
                image: "images/WOOSEA Women's Split Bodycon Mermaid Evening Dress royal blue.webp"
            }
        ]
    },
    {
        id: 35,
        category: "women",
        type: "fashion",
        brand: "WOOSEA",
        name: "Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress",
        description: "A high-neck interpretation of the classic mermaid evening gown. Understated from the front — unforgettable from behind.",
        price: "Check Price",
        badge: "Style Inspiration",
        trending: "Trending Now",
        image1: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress black.webp",
        image2: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress black.webp",
        affiliateLink: "https://www.amazon.com/WOOSEA-Bodycon-Mermaid-Evening-Cocktail/dp/B07HFQSDZ6?tag=seleneluxe05-20",
        buttonText: "Shop on Amazon",
        variants: [
            {
                color: "Purple",
                colorCode: "#800080",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress purple.webp"
            },
            {
                color: "Green",
                colorCode: "#008000",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress green.webp"
            },
            {
                color: "Red",
                colorCode: "#ff0000",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress red.webp"
            },
            {
                color: "Black",
                colorCode: "#000000",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress black.webp"
            },
            {
                color: "Navy Blue",
                colorCode: "#000080",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress navy blue.webp"
            },
            {
                color: "Royal Blue",
                colorCode: "#4169E1",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress royal blue.webp"
            },
            {
                color: "Burgundy Dark",
                colorCode: "#4a0404",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress burgundy.webp"
            },
            {
                color: "Burgundy",
                colorCode: "#800020",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress burgundy2.webp"
            },
            {
                color: "Magenta",
                colorCode: "#ff00ff",
                image: "images/WOOSEA Women's High Neck Split Bodycon Mermaid Evening Cocktail Long Dress magenta.webp"
            }
        ]
    },
    // SUMMER DRESSES
    {
        id: 36,
        category: "women",
        type: "fashion",
        brand: "Summer Collection",
        name: "The Bowknot Lace Mini Dress",
        description: "A playful lace mini dress with a dainty bowknot detail. Light as air, designed for golden-hour moments.",
        price: "Check Price",
        badge: "Summer Essential",
        trending: "Vacation Outfits ↑700%",
        image1: "images/summer dress 1.webp",
        image2: "images/summer dress 1.webp",
        affiliateLink: "https://a.co/d/0atlL5m0",
        buttonText: "Shop on Amazon"
    },
    {
        id: 37,
        category: "women",
        type: "fashion",
        brand: "Summer Collection",
        name: "The Flowy Tiered Maxi Dress",
        description: "A cascading tiered maxi dress that moves with every step. This is the dress that photographs itself.",
        price: "Check Price",
        badge: "Summer Essential",
        trending: "Vacation Outfits ↑700%",
        image1: "images/summer dress 2.webp",
        image2: "images/summer dress 2.webp",
        affiliateLink: "https://a.co/d/0do0Lk0K",
        buttonText: "Shop on Amazon"
    },
    {
        id: 38,
        category: "women",
        type: "fashion",
        brand: "Summer Collection",
        name: "The Crochet Tassel Maxi Dress",
        description: "Hand-crafted crochet texture meets a dramatic tassel trim. A bohemian statement for the woman who dresses with intention.",
        price: "Check Price",
        badge: "Summer Essential",
        trending: "Vacation Outfits ↑700%",
        image1: "images/summer dress 3.webp",
        image2: "images/summer dress 3.webp",
        affiliateLink: "https://a.co/d/08wyP2Yr",
        buttonText: "Shop on Amazon"
    },
    {
        id: 39,
        category: "women",
        type: "fashion",
        brand: "Summer Collection",
        name: "The Bohemian Halter Mini Dress",
        description: "A breezy halter-neck mini in soft drape fabric. Carefree silhouette, careful construction.",
        price: "Check Price",
        badge: "Summer Essential",
        trending: "Vacation Outfits ↑700%",
        image1: "images/summer dress 4.webp",
        image2: "images/summer dress 4.webp",
        affiliateLink: "https://a.co/d/05l2Bh9T",
        buttonText: "Shop on Amazon"
    },
    {
        id: 40,
        category: "women",
        type: "fashion",
        brand: "TANKANEO",
        name: "Cropped Cotton Collared Button-Down Blouse",
        description: "A cropped cotton blouse with a classic collared neckline — the foundational piece of the Blush & Ivory Edit. Clean, crisp, and endlessly versatile.",
        price: "Check Price",
        badge: "Style Inspiration",
        trending: "Old Money Summer ↑400%",
        image1: "images/e6156b53-34f7-4e37-bbf2-1ec17640a4cc.jpg",
        image2: "images/e6156b53-34f7-4e37-bbf2-1ec17640a4cc.jpg",
        outfitId: "blush-ivory-edit",
        affiliateLink: "https://a.co/d/014lDOPH",
        buttonText: "Shop on Amazon"
    },

    // HOME & LIFESTYLE
    {
        id: 41,
        category: "home",
        type: "lifestyle",
        brand: "Luckystyle",
        name: "Dimmable Arc Floor Lamp with Remote",
        description: "A sleek dimmable arc floor lamp with warm LED illumination and full remote control. Instantly elevates any living space with ambient, directional light.",
        price: "Check Price",
        badge: "Home Edit",
        image1: "images/lamp1.jpg",
        image2: "images/lamp1.jpg",
        affiliateLink: "https://a.co/d/05hw3ndJ",
        buttonText: "Shop on Amazon"
    },
    {
        id: 42,
        category: "home",
        type: "lifestyle",
        brand: "Kockuu",
        name: "6ft Artificial Olive Tree with White Pot",
        description: "A 6ft artificial olive tree potted in a clean white ceramic vessel. Brings the quiet grandeur of a Mediterranean courtyard into your interior — zero maintenance required.",
        price: "Check Price",
        badge: "Home Edit",
        image1: "images/plant1.jpg",
        image2: "images/plant1.jpg",
        affiliateLink: "https://a.co/d/02MSovsX",
        buttonText: "Shop on Amazon"
    },
    {
        id: 43,
        category: "home",
        type: "lifestyle",
        brand: "Victrola",
        name: "Willow Retro Wood Bluetooth Radio",
        description: "The Victrola Willow — a retro-wood Bluetooth radio with built-in speakers. Vintage aesthetic, modern wireless streaming. A room statement as much as a music player.",
        price: "Check Price",
        badge: "Home Edit",
        image1: "images/radio1.jpg",
        image2: "images/radio1.jpg",
        affiliateLink: "https://a.co/d/005FR4N6",
        buttonText: "Shop on Amazon"
    },
    // LIPSTICK — MAYBELLINE SUPERSTAY MATTE INK
    {
        id: 44,
        category: "cosmetics",
        type: "lifestyle",
        brand: "MAYBELLINE",
        name: "SuperStay Matte Ink — Shade 115 Founder",
        description: "A deep wine-dark liquid lipstick with up to 16 hours of no-transfer matte wear. Shade 115 Founder lays down velvety colour with the brand's precision arrow applicator — bold, clean, and built to last.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Matte Lips ↑",
        image1: "images/cosmetics1.jpg",
        image2: "images/cosmetics1.jpg",
        affiliateLink: "https://amzn.to/43Pemts",
        buttonText: "Shop on Amazon"
    },
    {
        id: 45,
        category: "cosmetics",
        type: "lifestyle",
        brand: "MAYBELLINE",
        name: "SuperStay Matte Ink — Shade 55 Composer",
        description: "An intense indigo-purple liquid lipstick for those who wear their mood on their lips. Up to 16 hours of saturated matte colour with zero transfer — a statement shade formulated to hold.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Bold Lips ↑",
        image1: "images/cosmetics2.jpg",
        image2: "images/cosmetics2.jpg",
        affiliateLink: "https://amzn.to/4uPUNvX",
        buttonText: "Shop on Amazon"
    },
    {
        id: 46,
        category: "cosmetics",
        type: "lifestyle",
        brand: "MAYBELLINE",
        name: "SuperStay Matte Ink — Shade 10 Dreamer",
        description: "A warm mid-tone pink that flatters every complexion. Up to 16 hours of flawless matte wear — the Dreamer shade is effortlessly wearable from morning coffee to evening out.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics3.jpg",
        image2: "images/cosmetics3.jpg",
        affiliateLink: "https://amzn.to/4uRzZ7v",
        buttonText: "Shop on Amazon"
    },
    {
        id: 47,
        category: "cosmetics",
        type: "lifestyle",
        brand: "MAYBELLINE",
        name: "SuperStay Matte Ink — Shade 160 Mover",
        description: "A sophisticated mauve-brown that sits beautifully on all skin tones. Shade 160 Mover delivers 16 hours of transfer-proof matte colour — the understated everyday shade that always gets noticed.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics4.jpg",
        image2: "images/cosmetics4.jpg",
        affiliateLink: "https://amzn.to/3SkRb7N",
        buttonText: "Shop on Amazon"
    },
    // LIPSTICK — L'ORÉAL PARIS COLOR RICHE
    {
        id: 48,
        category: "cosmetics",
        type: "lifestyle",
        brand: "L'ORÉAL PARIS",
        name: "Color Riche Lipstick — Shade 850 Brazil Nut",
        description: "A warm earthy brown-nude that brings understated elegance to any look. Formulated with hydrating and nourishing ingredients — the quintessential quiet luxury lip colour.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics5.jpg",
        image2: "images/cosmetics5.jpg",
        affiliateLink: "https://amzn.to/4b1u9Jx",
        buttonText: "Shop on Amazon"
    },
    {
        id: 49,
        category: "cosmetics",
        type: "lifestyle",
        brand: "L'ORÉAL PARIS",
        name: "Color Riche Lipstick — Shade 137 Berry Parisienne",
        description: "A bold berry-magenta formulated with Omega-3, Vitamin E, and Argan Oil. This luxurious creamy-satin lipstick delivers vibrant colour while caring for the lips in every swipe.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics6.jpg",
        image2: "images/cosmetics6.jpg",
        affiliateLink: "https://amzn.to/4vfXl7K",
        buttonText: "Shop on Amazon"
    },
    {
        id: 50,
        category: "cosmetics",
        type: "lifestyle",
        brand: "L'ORÉAL PARIS",
        name: "Color Riche Lipstick — Shade 417 Peach Fuzz",
        description: "A soft peach-nude that works on every skin tone. Shade 417 Peach Fuzz combines luxurious moisture with vibrant satin-finish colour — Colour Riche's signature blend of beauty and comfort.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics7.jpg",
        image2: "images/cosmetics7.jpg",
        affiliateLink: "https://amzn.to/4uNP9uv",
        buttonText: "Shop on Amazon"
    },
    {
        id: 51,
        category: "cosmetics",
        type: "lifestyle",
        brand: "L'ORÉAL PARIS",
        name: "Color Riche Lipstick — Shade 135 Ballerina Shoes",
        description: "A delicate sheer-pink with a luminous pearl finish. Shade 135 Ballerina Shoes adds a touch of refined femininity — light-catching, softly radiant, and elegant on all skin tones.",
        price: "Check Price",
        badge: "Beauty Edit",
        image1: "images/cosmetics8.jpg",
        image2: "images/cosmetics8.jpg",
        affiliateLink: "https://amzn.to/4eyAtJB",
        buttonText: "Shop on Amazon"
    },
    {
        id: 53,
        category: "cosmetics",
        type: "lifestyle",
        brand: "BIODANCE",
        name: "Bio-Collagen Real Deep Mask",
        description: "A K-beauty overnight ritual that transforms skin as you sleep. Real collagen-infused bio-hydrogel sheets adhere to every contour, delivering deep moisture, visibly plumper texture and refined pores by morning. Four single-use masks — each one a night of pure skin recovery.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Glass Skin ↑",
        image1: "images/cosmetics9.jpg",
        image2: "images/cosmetics9.jpg",
        affiliateLink: "https://amzn.to/44GLVOB",
        buttonText: "Shop on Amazon"
    },
    {
        id: 54,
        category: "cosmetics",
        type: "lifestyle",
        brand: "CERAVE",
        name: "Moisturizing Cream",
        description: "The dermatologist-trusted formula that has become a medicine cabinet icon. Three essential ceramides and hyaluronic acid work in synergy to restore the skin's natural barrier, delivering long-lasting moisture in a fragrance-free, non-comedogenic formula that suits every skin type.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Skincare Essentials ↑",
        image1: "images/cosmetics10.jpg",
        image2: "images/cosmetics10.jpg",
        affiliateLink: "https://amzn.to/441AJvS",
        buttonText: "Shop on Amazon"
    },
    {
        id: 55,
        category: "cosmetics",
        type: "lifestyle",
        brand: "DR.ALTHEA",
        name: "345 Relief Cream",
        description: "A post-acne recovery essential from the heart of Korean dermocosmetics. Powered by regenerative PDRN technology, centella asiatica and niacinamide, this vegan cream targets blemishes, calms redness and fades residual marks — restoring clarity and resilience with every application.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "K-Beauty ↑",
        image1: "images/cosmetics11.jpg",
        image2: "images/cosmetics11.jpg",
        affiliateLink: "https://amzn.to/4eNmtMh",
        buttonText: "Shop on Amazon"
    },
    {
        id: 56,
        category: "cosmetics",
        type: "lifestyle",
        brand: "BYOMA",
        name: "Moisturizing Gel Cream",
        description: "A barrier-first formula built for skin that needs to heal. BYOMA's clinically developed tri-ceramide complex and niacinamide replenish the skin barrier while green tea provides antioxidant calm — entirely alcohol-free, oil-free and weightlessly effective for compromised or sensitive skin.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Barrier Repair ↑",
        image1: "images/cosmetics12.jpg",
        image2: "images/cosmetics12.jpg",
        affiliateLink: "https://amzn.to/4gvolvJ",
        buttonText: "Shop on Amazon"
    },
    {
        id: 57,
        category: "cosmetics",
        type: "lifestyle",
        brand: "FLORENCE",
        name: "Vitamin C Serum For Face",
        description: "A brightening powerhouse in every drop. This potent vitamin C serum pairs free-radical-fighting antioxidants with hyaluronic acid and vitamin E to visibly fade dark spots, even skin tone and smooth fine lines — leaving skin luminous, hydrated and unapologetically radiant.",
        price: "Check Price",
        badge: "Beauty Edit",
        trending: "Vitamin C ↑",
        image1: "images/cosmetics13.jpg",
        image2: "images/cosmetics13.jpg",
        affiliateLink: "https://amzn.to/4xSl27M",
        buttonText: "Shop on Amazon"
    },
    // HOME — GARDEN
    {
        id: 52,
        category: "home",
        type: "lifestyle",
        brand: "BOUNTIFUL BOUGHS",
        name: "Solar Garden Turtle Statue with Succulent Charm",
        description: "A hand-painted resin garden statue featuring a charming turtle adorned with vivid succulents. Solar-powered with auto-lighting up to 10 hours — IP65 waterproof and UV-resistant for year-round outdoor display.",
        price: "Check Price",
        badge: "Home Edit",
        image1: "images/turtle1.jpg",
        image2: "images/turtle1.jpg",
        affiliateLink: "https://amzn.to/4ekaSFn",
        buttonText: "Shop on Amazon"
    },
    {
        id: 58,
        category: "women",
        type: "fashion",
        brand: "Colornival",
        name: "Elegant Lace Beach Cover Up",
        description: "Loose, long design, one size fits all heights and body shapes. Perfect for wearing at tanning salons, beaches, pools, or swimming pools. The unique lace floral pattern paired with bikinis, camisoles, or shorts enhances your fashion appeal. If you're wearing a bikini on a beach vacation, this beach cover-up not only protects you from strong UV rays but also makes you stand out in the crowd. A great gift for mothers, wives, girlfriends, or the woman you love. Whether for daily wear or vacation, it will surely bring you joy",
        badge: "New Arrival",
        image1: "images/colornival-elegant-lace-beach-cover-up.png",
        image2: "images/colornival-elegant-lace-beach-cover-up.png",
        affiliateLink: "https://amzn.to/44HlCrG",
        buttonText: "Shop on Amazon"
    },
    {
        id: 59,
        category: "men",
        type: "fashion",
        brand: "COOFANDY",
        name: "Men's Linen Shirts",
        description: "These linen shirts are perfect for summer. Light, breathable, and great for any occasion!",
        price: "Check Price",
        image1: "images/coofandy-men-s-linen-shirts.jpg",
        image2: "images/coofandy-men-s-linen-shirts.jpg",
        affiliateLink: "https://amzn.to/4yfZoKV",
        buttonText: "Shop on Amazon"
    },
];

const outfits = [
    {
        id: "birmingham-edit",
        name: "The Birmingham Edit",
        description: "Inspired by the sharp, authoritative style of the 1920s Birmingham gentleman. This collection features heavy wools, structured tailoring, and timeless accessories for a commanding look.",
        heroImage: "images/outfit1.webp",
        category: "Men"
    },
    {
        id: "navy-ivory-edit",
        name: "The Navy & Ivory Edit",
        description: "A sophisticated study in contrast. This look features a deep navy wool-blend maxi coat layered over crisp ivory wide-leg trousers, accented by a bold lime green top-handle bag for a modern, architectural finish.",
        heroImage: "images/navy-ivory-hero.webp",
        category: "Women"
    },
    {
        id: "pink-meadow-edit",
        name: "The Pink Meadow Edit",
        description: "A whimsical, vintage-inspired collection for your little one. This edit pairs a tan gingham blouse with a sweet suspender skirt, finished with charming accessories like a little bear crossbody and ruffle-trim socks.",
        heroImage: "images/pink-meadow-hero.webp",
        category: "Kids"
    },
    {
        id: "blush-ivory-edit",
        name: "The Blush & Ivory Edit",
        description: "A soft, feminine study in contrast. This edit pairs a blush pink cropped cotton button-down blouse with flowing ivory wide-leg pleated trousers — an effortlessly polished look that bridges casual comfort with refined elegance.",
        heroImage: "images/blush-ivory-hero.webp",
        heroVideo: "images/A_fast_paced_high_fashion_cin.mp4",
        category: "Women"
    },
    {
        id: "cosmetics-skincare-edit",
        name: "The Cosmetics & Skincare Edit",
        description: "A curated selection of premium Korean beauty essentials. This collection features hydrating lip masks and powerful snail mucin essences for radiant, healthy skin.",
        heroImage: "images/cosmetics-hero.webp",
        category: "Beauty"
    }
];